# Generated by Django 4.2.4 on 2023-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=20)),
                ("LastName", models.CharField(max_length=20)),
                ("Department", models.CharField(max_length=20)),
                ("Marks", models.IntegerField()),
            ],
        ),
    ]
